# Tankoban main-app source + header lists.
# Extracted from CMakeLists.txt (REPO_STRUCTURE_CLEANUP P3, 2026-05-29) to keep the root
# CMakeLists lean + reduce merge collisions on the source list. include()d before
# qt_add_executable(Tankoban) so SOURCES/HEADERS land in the parent scope.
# Add a source/header HERE, not in CMakeLists.txt.

set(SOURCES
    src/main.cpp
    src/core/DebugLogBuffer.cpp
    src/core/JsonlEventLog.cpp
    src/devtools/DevControlServer.cpp
    src/devtools/UiInteractionDispatcher.cpp
    src/devtools/SystemIntrospection.cpp
    src/devtools/HangWatchdog.cpp
    src/core/JsonStore.cpp
    src/core/CoreBridge.cpp
    src/core/LibraryScanner.cpp
    src/core/library/VideoCategory.cpp
    src/core/library/VideoCategoryStore.cpp
    src/core/library/VideoClassifier.cpp
    src/core/VideosScanner.cpp
    src/core/ScannerUtils.cpp
    src/core/PosterFetcher.cpp
    src/core/PosterCache.cpp
    src/core/ArchiveReader.cpp
    src/ui/MainWindow.cpp
    src/ui/PerModeNavController.cpp
    src/ui/Theme.cpp
    src/ui/GlassBackground.cpp
    src/ui/RootFoldersOverlay.cpp
    src/ui/ContextMenuHelper.cpp
    src/ui/widgets/FadingStackedWidget.cpp
    src/ui/widgets/LibraryListView.cpp
    src/ui/widgets/SidebarDrawer.cpp
    src/ui/widgets/Toast.cpp
    src/ui/widgets/ThemePicker.cpp
    src/ui/widgets/ComicsSeriesViewLoadingOverlay.cpp
    src/ui/pages/ComicsPage.cpp
    src/ui/pages/BooksPage.cpp
    src/ui/pages/VideosPage.cpp
    src/ui/pages/OrganisePage.cpp
    src/ui/pages/CategoryEditorPage.cpp
    src/ui/pages/PosterPickerPopover.cpp
    src/ui/pages/SeriesView.cpp
    src/ui/pages/TileCard.cpp
    src/ui/pages/TileStrip.cpp
    src/ui/pages/ShowView.cpp
    src/ui/readers/ComicReader.cpp
    src/ui/readers/BookReader.cpp
    src/ui/readers/BookBridge.cpp
    src/core/tts/EdgeTtsClient.cpp
    src/core/tts/EdgeTtsWorker.cpp
    src/ui/readers/ScrollStripCanvas.cpp
    src/ui/readers/SmoothScrollArea.cpp
    src/ui/readers/DecodeTask.cpp
    src/ui/readers/PageCache.cpp
    src/ui/readers/ThumbnailGenerator.cpp
    src/core/EpubParser.cpp
    src/ui/pages/TankorentPage.cpp
    src/ui/pages/IndexerStatusPanel.cpp
    src/ui/pages/tankorent/TorrentPropertiesWidget.cpp
    src/ui/pages/tankorent/TorrentFilesTab.cpp
    src/ui/pages/tankorent/TorrentTrackersTab.cpp
    src/ui/pages/tankorent/TorrentPeersTab.cpp
    src/ui/pages/tankorent/TorrentGeneralTab.cpp
    src/core/TorrentIndexer.cpp
    src/core/TankorentSearchService.cpp
    src/core/indexers/TorrentsCsvIndexer.cpp
    src/core/indexers/NyaaIndexer.cpp
    src/core/indexers/PirateBayIndexer.cpp
    src/core/indexers/YtsIndexer.cpp
    src/core/indexers/EztvIndexer.cpp
    src/core/indexers/X1337xIndexer.cpp
    src/core/indexers/ExtTorrentsIndexer.cpp
    src/core/indexers/CloudflareCookieHarvester.cpp
    src/ui/player/SidecarProcess.cpp
    # MAKE_MPV_SOLO Task 8.B (2026-05-02) — Windows audio device-change
    # watcher (IMMNotificationClient COM listener + Qt-thread marshaling).
    # Closes the deferred per-device-delay-recall deliverable from Task 8.
    src/ui/player/AudioDeviceWatcher.cpp
    src/ui/player/ShmFrameReader.cpp
    src/ui/player/OverlayShmReader.cpp
    src/ui/player/FrameCanvas.cpp
    src/ui/player/VideoPlayer.cpp
    src/ui/player/VolumeHud.cpp
    src/ui/player/SeekSlider.cpp
    src/ui/player/KeyBindings.cpp
    src/ui/player/VsyncTimingLogger.cpp
    src/ui/player/CenterFlash.cpp
    src/ui/player/LoadingOverlay.cpp
    src/ui/player/ToastHud.cpp
    src/ui/player/PlaylistDrawer.cpp
    src/ui/player/SubtitleOverlay.cpp
    # VIDEO_HUD_MINIMALIST 2026-04-25 — TrackPopover / FilterPopover /
    # EqualizerPopover / SubtitleMenu replaced by SubtitlePopover +
    # AudioPopover + SettingsPopover (merged subtitle list absorbs the
    # SubtitleMenu external/addon-subs + load-from-file functionality).
    src/ui/player/SubtitlePopover.cpp
    src/ui/player/AudioPopover.cpp
    src/ui/player/SettingsPopover.cpp
    # MAKE_MPV_SOLO Task 9 (2026-05-01) — brightness-only filter popover.
    # Hemanth-narrowed scope revert of VIDEO_HUD_MINIMALIST Phase 1's
    # filter-stack removal; contrast/saturation stay removed.
    src/ui/player/BrightnessPopover.cpp
    src/ui/player/VideoContextMenu.cpp
    src/ui/player/OpenUrlDialog.cpp
    src/ui/player/KeybindingEditor.cpp
    src/ui/player/StatsBadge.cpp
    src/core/torrent/TorrentEngine.cpp
    src/core/torrent/TorrentClient.cpp
    src/core/torrent/TorrentRepository.cpp
    src/core/torrent/LegacyImporter.cpp
    src/core/queue/TransferItem.h
    src/core/queue/TransferLane.h
    src/core/queue/TransferQueue.h
    src/core/queue/TransferQueue.cpp
    src/ui/dialogs/AddTorrentDialog.cpp
    src/ui/dialogs/AddFromUrlDialog.cpp
    src/ui/dialogs/StreamRescueProgressDialog.cpp
    src/ui/dialogs/SpeedLimitDialog.cpp
    src/ui/dialogs/SeedingRulesDialog.cpp
    src/ui/dialogs/QueueLimitsDialog.cpp
    src/ui/dialogs/HistoryDialog.cpp
    src/core/manga/WeebCentralScraper.cpp
    src/core/manga/ReadComicsScraper.cpp
    src/core/manga/ReadAllComicsScraper.cpp
    src/core/manga/MangaSeriesDetail.cpp
    src/core/manga/MangaSourceRegistry.cpp
    src/core/manga/ComicsLibraryRecord.cpp
    src/core/manga/ComicsTankoyomiLibrary.cpp
    src/core/manga/WesternLibrary.cpp
    src/core/manga/MangaPosterCache.cpp
    src/core/manga/MangaDownloader.cpp
    src/core/manga/MangaDownloadIndex.cpp
    src/core/manga/PremiumCatalog.cpp
    src/core/manga/TorrentRequestLedger.cpp
    src/core/manga/TorrentVolumeProvider.cpp
    src/core/manga/MangaTransferCoordinator.cpp
    src/core/manga/PremiumArchiveValidator.cpp
    src/core/manga/PremiumCoverExtractor.cpp
    src/core/manga/NyaaRuntimeSource.cpp
    src/core/manga/WeebCentralVolumePacker.cpp
    src/core/manga/ComicsPrePivotMigrator.cpp
    src/core/manga/TrustedUploaders.cpp
    src/core/manga/VolumeQualityClassifier.cpp
    src/core/manga/MangaCatalogTypes.cpp
    src/core/manga/LocalMangaCatalogLoader.cpp
    src/core/manga/WesternCatalogLoader.cpp
    src/core/manga/WesternSeriesParse.cpp
    src/core/manga/GetComicsParse.cpp
    src/core/manga/GetComicsResolver.cpp
    src/core/manga/ReadComicsPageParse.cpp
    src/core/manga/WesternVolumeDownloader.cpp
    src/core/manga/LocalMangaCatalogIndex.cpp
    src/core/manga/mangafire/MangaFireCatalogClient.cpp
    src/core/manga/mangafire/MangaWeebCentralResolver.cpp
    src/core/manga/anilist/AniListClient.cpp
    src/core/manga/anilist/AniListParser.cpp
    src/core/manga/anilist/AniListCache.cpp
    src/core/manga/anilist/AniListVolumeMapper.cpp
    src/core/manga/mangaupdates/MangaUpdatesStatusParser.cpp
    src/core/manga/mangaupdates/MangaUpdatesDisambiguator.cpp
    src/core/manga/mangaupdates/MangaUpdatesClient.cpp
    src/core/manga/mangaupdates/JapaneseTitlePicker.cpp
    src/core/manga/mangaupdates/VolumeMetadataResolver.cpp
    src/core/manga/wikidata/WikidataClient.cpp
    src/core/manga/wikidata/WikidataCache.cpp
    src/core/manga/wikipedia/WikipediaParser.cpp
    src/core/manga/wikipedia/WikipediaResolver.cpp
    src/core/book/AnnaArchiveScraper.cpp
    src/core/book/AaSlowDownloadWaitHandler.cpp
    src/core/book/LibGenScraper.cpp
    src/core/book/AbbScraper.cpp
    src/core/book/TankorentBookScraper.cpp
    src/core/book/BookDownloader.cpp
    src/core/book/BookSearchAggregator.cpp
    src/core/book/BooksCatalogueLibraryStore.cpp
    src/core/book/CatalogueRecord.cpp
    src/core/book/FictionDbClient.cpp
    src/core/book/BookSeriesIndex.cpp
    src/core/book/BookSeriesIndexBuilder.cpp
    src/core/book/BookCatalogueAggregator.cpp
    src/core/net/NetSeam.cpp
    src/core/net/HttpFileDownloader.cpp
    src/ui/dialogs/MangaTransferDialog.cpp
    src/ui/dialogs/AddAddonDialog.cpp
    src/ui/pages/comics/SidecarMeta.cpp
    src/ui/pages/comics/ComicsTankoyomiSearchWidget.cpp
    src/ui/pages/comics/ComicsDownloadsPage.cpp
    src/ui/pages/comics/VolumeTile.cpp
    src/ui/pages/comics/ComicsSeriesView.cpp
    src/ui/pages/comics/ComicsSourceCard.cpp
    src/ui/pages/comics/ComicsSourcesPanel.cpp
    src/ui/pages/tankoyomi/ChapterDownloadIndicator.cpp
    src/ui/pages/tankoyomi/ChapterRangeDialog.cpp
    src/ui/pages/books/BookCatalogueSearchWidget.cpp
    src/ui/pages/books/BookCatalogueDetailView.cpp
    src/ui/pages/books/BookSeriesDetailView.cpp
    src/ui/pages/books/BooksDownloadsPage.cpp
    src/ui/pages/TankoLibraryPage.cpp
    src/ui/pages/tankolibrary/BookResultsGrid.cpp
    src/ui/pages/tankolibrary/TransfersView.cpp
    src/core/stream/MetaAggregator.cpp
    # STREAM_SERVER_PIVOT Phase 3 (2026-04-25) — legacy libtorrent stream
    # engine deleted (StreamEngine, StreamHttpServer, StreamPieceWaiter,
    # StreamPrioritizer, StreamSeekClassifier, StreamSession).
    # THEATRE_STREAMING_RESTORE P0 (2026-06-09) — the Stremio stream-server
    # subprocess layer (StreamServerProcess/Client/Engine), deleted in
    # THEATRE_DOWNLOAD_ONLY P2.2 (64213b5, 2026-05-29), is restored to bring
    # back instant-play streaming alongside download-only (Hemanth 2026-06-09).
    src/core/stream/stremio/StreamServerProcess.cpp
    src/core/stream/stremio/StreamServerClient.cpp
    src/core/stream/stremio/StreamServerEngine.cpp
    src/core/stream/StreamLibrary.cpp
    src/core/stream/addon/AddonTransport.cpp
    src/core/stream/addon/AddonRegistry.cpp
    src/core/stream/CatalogAggregator.cpp
    src/core/stream/StreamAggregator.cpp
    src/core/stream/AnimeCatalogResolver.cpp
    src/core/stream/AnimeIdMapCache.cpp
    src/core/stream/BulkSourceCollector.cpp
    src/core/stream/BulkPackVerifier.cpp
    src/core/stream/StreamPackParser.cpp
    src/core/stream/SubtitlesAggregator.cpp
    src/core/stream/StreamDownloadIndex.cpp
    src/core/stream/QualityScorer.cpp
    src/core/stream/AutoSourcePicker.cpp
    src/core/stream/EpisodeDisplayState.cpp
    src/core/stream/UnifiedProgressStore.cpp
    src/core/stream/StreamRescueScanner.cpp
    src/core/stream/StreamBulkPlan.cpp
    src/core/stream/PackClassifier.cpp
    src/core/stream/UnifiedPackSearchEngine.cpp
    src/core/stream/TitleMetadataEstimator.cpp
    src/ui/pages/StreamPage.cpp
    src/ui/pages/stream/StreamLibraryLayout.cpp
    src/ui/pages/stream/StreamDownloadsPage.cpp
    # DOWNLOADS_OVERHAUL_V2 T8 (2026-06-11) — pack-first Season Checkout dialog.
    src/ui/pages/stream/SeasonCheckoutPanel.cpp
    src/ui/pages/stream/StreamSearchWidget.cpp
    src/ui/pages/stream/StreamDetailView.cpp
    # THEATRE_STREAMING_RESTORE P1 (2026-06-09) — restored streaming controller.
    src/ui/pages/stream/StreamPlayerController.cpp
    src/ui/pages/stream/TorrentPackPicker.cpp
    src/ui/pages/stream/TheatreDownloadPanel.cpp
    src/ui/pages/stream/PackListItem.cpp
    src/ui/pages/stream/EpisodeTile.cpp
    src/ui/pages/stream/StreamSourceChoice.cpp
    src/ui/pages/stream/StreamSourceCard.cpp
    src/ui/pages/stream/StreamSourceList.cpp
    src/ui/pages/stream/StreamContinueStrip.cpp
    src/ui/pages/stream/AddonManagerScreen.cpp
    src/ui/pages/stream/AddonDetailPanel.cpp
    src/ui/pages/stream/StreamHomeBoard.cpp
    src/ui/pages/stream/CatalogBrowseScreen.cpp
)

set(HEADERS
    src/core/DebugLogBuffer.h
    src/core/JsonlEventLog.h
    src/devtools/DevControlServer.h
    src/devtools/UiInteractionDispatcher.h
    src/devtools/SystemIntrospection.h
    src/devtools/HangWatchdog.h
    src/devtools/IDevInspectable.h
    src/core/JsonStore.h
    src/core/CoreBridge.h
    src/core/LibraryScanner.h
    src/core/library/VideoCategory.h
    src/core/library/VideoCategoryStore.h
    src/core/library/VideoClassifier.h
    src/core/VideosScanner.h
    src/core/ScannerUtils.h
    src/core/PosterFetcher.h
    src/core/PosterCache.h
    src/core/ArchiveReader.h
    src/ui/MainWindow.h
    src/ui/LayerEntry.h
    src/ui/PerModeNavController.h
    src/ui/GlassBackground.h
    src/ui/RootFoldersOverlay.h
    src/ui/ContextMenuHelper.h
    src/ui/widgets/FadingStackedWidget.h
    src/ui/widgets/LibraryListView.h
    src/ui/widgets/SidebarDrawer.h
    src/ui/widgets/Toast.h
    src/ui/pages/ComicsPage.h
    src/ui/pages/BooksPage.h
    src/ui/pages/VideosPage.h
    src/ui/pages/OrganisePage.h
    src/ui/pages/CategoryEditorPage.h
    src/ui/pages/PosterPickerPopover.h
    src/ui/pages/SeriesView.h
    src/ui/pages/TileCard.h
    src/ui/pages/TileStrip.h
    src/ui/pages/ShowView.h
    src/ui/readers/ComicReader.h
    src/ui/readers/comic_progress_key.h
    src/ui/readers/BookReader.h
    src/ui/readers/BookBridge.h
    src/core/tts/EdgeTtsClient.h
    src/core/tts/EdgeTtsWorker.h
    src/ui/readers/SmoothScrollArea.h
    src/ui/readers/DecodeTask.h
    src/ui/readers/PageCache.h
    src/ui/readers/ThumbnailGenerator.h
    src/core/EpubParser.h
    src/ui/pages/TankorentPage.h
    src/ui/pages/IndexerStatusPanel.h
    src/ui/pages/tankorent/TorrentPropertiesWidget.h
    src/ui/pages/tankorent/TorrentFilesTab.h
    src/ui/pages/tankorent/TorrentTrackersTab.h
    src/ui/pages/tankorent/TorrentPeersTab.h
    src/ui/pages/tankorent/TorrentGeneralTab.h
    src/core/TorrentResult.h
    src/core/TorrentIndexer.h
    src/core/TankorentSearchService.h
    src/core/indexers/TorrentsCsvIndexer.h
    src/core/indexers/NyaaIndexer.h
    src/core/indexers/PirateBayIndexer.h
    src/core/indexers/YtsIndexer.h
    src/core/indexers/EztvIndexer.h
    src/core/indexers/X1337xIndexer.h
    src/core/indexers/ExtTorrentsIndexer.h
    src/core/indexers/CloudflareCookieHarvester.h
    src/ui/player/IPlayerBackend.h
    src/ui/player/SidecarProcess.h
    src/ui/player/AudioDeviceWatcher.h
    src/ui/player/ShmFrameReader.h
    src/ui/player/FrameCanvas.h
    src/ui/player/VideoPlayer.h
    src/ui/player/VolumeHud.h
    src/ui/player/SeekSlider.h
    src/ui/player/CenterFlash.h
    src/ui/player/PlaylistDrawer.h
    src/ui/player/SubtitleOverlay.h
    src/ui/player/SubtitlePopover.h
    src/ui/player/AudioPopover.h
    src/ui/player/SettingsPopover.h
    src/ui/player/BrightnessPopover.h
    src/ui/player/VideoContextMenu.h
    src/ui/player/KeybindingEditor.h
    src/ui/player/StatsBadge.h
    src/core/torrent/TorrentEngine.h
    src/core/torrent/TorrentClient.h
    src/ui/dialogs/AddTorrentDialog.h
    src/ui/dialogs/AddFromUrlDialog.h
    src/ui/dialogs/StreamRescueProgressDialog.h
    src/ui/dialogs/SpeedLimitDialog.h
    src/ui/dialogs/SeedingRulesDialog.h
    src/ui/dialogs/QueueLimitsDialog.h
    src/ui/dialogs/HistoryDialog.h
    src/core/manga/MangaResult.h
    src/core/manga/MangaScraper.h
    src/core/manga/MangaSeriesDetail.h
    src/core/manga/MangaSourceRegistry.h
    src/core/manga/ComicsLibraryRecord.h
    src/core/manga/ComicsTankoyomiLibrary.h
    src/core/manga/MangaPosterCache.h
    src/core/manga/WeebCentralScraper.h
    src/core/manga/ReadComicsScraper.h
    src/core/manga/ReadAllComicsScraper.h
    src/core/manga/MangaDownloader.h
    src/core/manga/MangaDownloadIndex.h
    src/core/manga/PremiumCatalog.h
    src/core/manga/PremiumCatalogSchema.h
    src/core/manga/TorrentRequestLedger.h
    src/core/manga/TorrentVolumeProvider.h
    src/core/manga/MangaTransferCoordinator.h
    src/core/manga/PremiumArchiveValidator.h
    src/core/manga/PremiumCoverExtractor.h
    src/core/manga/NyaaRuntimeSource.h
    src/core/manga/WeebCentralVolumePacker.h
    src/core/manga/ComicsPrePivotMigrator.h
    src/core/manga/CanonicalChapterKey.h
    src/core/manga/anilist/AniListTypes.h
    src/core/manga/anilist/AniListClient.h
    src/core/manga/anilist/AniListParser.h
    src/core/manga/anilist/AniListCache.h
    src/core/manga/anilist/AniListVolumeMapper.h
    src/core/manga/mangaupdates/MangaUpdatesTypes.h
    src/core/manga/mangaupdates/MangaUpdatesStatusParser.h
    src/core/manga/mangaupdates/MangaUpdatesDisambiguator.h
    src/core/manga/mangaupdates/MangaUpdatesClient.h
    src/core/manga/mangaupdates/VolumeMetadataResolver.h
    src/core/book/BookCatalogueResult.h
    src/core/book/BooksCatalogueLibraryStore.h
    src/core/book/CatalogueRecord.h
    src/core/book/SeriesDetector.h
    src/core/book/BookCatalogueAggregator.h
    src/core/book/BookResult.h
    src/core/book/BookScraper.h
    src/core/book/AnnaArchiveScraper.h
    src/core/book/AaSlowDownloadWaitHandler.h
    src/core/book/LibGenScraper.h
    src/core/book/AbbScraper.h
    src/core/book/TankorentBookScraper.h
    src/core/book/BookDownloader.h
    src/core/book/BookSearchAggregator.h
    src/core/net/NetSeam.h
    src/core/net/HttpFileDownloader.h
    src/ui/dialogs/MangaTransferDialog.h
    src/ui/dialogs/AddAddonDialog.h
    src/ui/pages/comics/SidecarMeta.h
    src/ui/pages/comics/ComicsTankoyomiSearchWidget.h
    src/ui/pages/comics/ComicsDownloadsPage.h
    src/ui/pages/comics/ComicsSeriesView.h
    src/ui/pages/comics/ComicsSourceCard.h
    src/ui/pages/comics/ComicsSourcesPanel.h
    src/ui/pages/tankoyomi/ChapterDownloadIndicator.h
    src/ui/pages/tankoyomi/ChapterRangeDialog.h
    src/ui/pages/books/BookCatalogueSearchWidget.h
    src/ui/pages/books/BookCatalogueDetailView.h
    src/ui/pages/books/BookSeriesDetailView.h
    src/ui/pages/books/BooksDownloadsPage.h
    src/ui/pages/TankoLibraryPage.h
    src/ui/pages/tankolibrary/BookResultsGrid.h
    src/ui/pages/tankolibrary/TransfersView.h
    src/core/stream/MetaAggregator.h
    # THEATRE_STREAMING_RESTORE P0 (2026-06-09) — Stremio stream-server headers
    # restored from 64213b5^ (see SOURCES note above).
    src/core/stream/stremio/StreamServerProcess.h
    src/core/stream/stremio/StreamServerClient.h
    src/core/stream/stremio/StreamServerEngine.h
    src/core/stream/StreamTypes.h
    src/core/stream/StreamTelemetryWriter.h
    src/core/stream/StreamLibrary.h
    src/core/stream/StreamProgress.h
    src/core/stream/addon/Manifest.h
    src/core/stream/addon/Descriptor.h
    src/core/stream/addon/ResourcePath.h
    src/core/stream/addon/StreamSource.h
    src/core/stream/addon/SubtitleInfo.h
    src/core/stream/addon/StreamInfo.h
    src/core/stream/addon/MetaItem.h
    src/core/stream/addon/AddonTransport.h
    src/core/stream/addon/AddonRegistry.h
    src/core/stream/CatalogAggregator.h
    src/core/stream/StreamAggregator.h
    src/core/stream/BulkSourceCollector.h
    src/core/stream/BulkPackVerifier.h
    src/core/stream/StreamPackParser.h
    src/core/stream/SubtitlesAggregator.h
    src/core/stream/StreamDownloadIndex.h
    src/core/stream/QualityScorer.h
    src/core/stream/AutoSourcePicker.h
    src/core/stream/UnifiedProgressStore.h
    src/core/stream/StreamRescueScanner.h
    src/core/stream/StreamBulkPlan.h
    src/core/stream/PackClassifier.h
    src/core/stream/UnifiedPackSearchEngine.h
    src/core/stream/TitleMetadataEstimator.h
    src/ui/pages/StreamPage.h
    src/ui/pages/stream/StreamLibraryLayout.h
    src/ui/pages/stream/StreamDownloadsPage.h
    # DOWNLOADS_OVERHAUL_V2 T8 (2026-06-11) — pack-first Season Checkout dialog.
    src/ui/pages/stream/SeasonCheckoutPanel.h
    src/ui/pages/stream/StreamSearchWidget.h
    src/ui/pages/stream/StreamDetailView.h
    # THEATRE_STREAMING_RESTORE P1 (2026-06-09) — restored streaming controller.
    src/ui/pages/stream/StreamPlayerController.h
    src/ui/pages/stream/TorrentPackPicker.h
    src/ui/pages/stream/TheatreDownloadPanel.h
    src/ui/pages/stream/PackListItem.h
    src/ui/pages/stream/EpisodeTile.h
    src/ui/pages/stream/StreamSourceChoice.h
    src/ui/pages/stream/StreamSourceCard.h
    src/ui/pages/stream/StreamSourceList.h
    src/ui/pages/stream/StreamContinueStrip.h
    src/ui/pages/stream/AddonManagerScreen.h
    src/ui/pages/stream/AddonDetailPanel.h
    src/ui/pages/stream/StreamHomeBoard.h
    src/ui/pages/stream/CatalogBrowseScreen.h
)
